# lexik_jwt_authentication:
#     secret_key: '%kernel.project_dir%/config/jwt/private.pem'  # Path to your private key
#     public_key: '%kernel.project_dir%/config/jwt/public.pem'   # Path to your public key
#     pass_phrase: 'your_passphrase'                             # Passphrase of your private key
#     token_ttl: 3600                                            # Time-to-live for the token

lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: email
    token_ttl: 3600
