security:
    enable_authenticator_manager: true

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/api/login
            stateless: true
            provider: users
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern: ^/api
            stateless: true
            jwt: ~

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: /api/login, roles: PUBLIC_ACCESS }
        - { path: /api/password-reset , roles: PUBLIC_ACCESS }
        - { path: /api/create-users, roles: PUBLIC_ACCESS }
        - { path: /api/liste-institut, roles: PUBLIC_ACCESS }
        - { path: /api/publishable-key, roles: PUBLIC_ACCESS }
        - { path: /api/create-payment-intent, roles: PUBLIC_ACCESS }
        
        - { path: /api/users, roles: PUBLIC_ACCESS }
        - { path: /api/create-institut, roles: PUBLIC_ACCESS }
        - { path: /api/create-demandeur, roles: PUBLIC_ACCESS }
        # - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
          
    role_hierarchy:
        ROLE_SUPER_ADMIN: ["ROLE_ADMIN", "ROLE_ALLOWED_TO_SWITCH"]
        ROLE_ADMIN: ROLE_ADMIN
        ROLE_INSTITUT: ROLE_INSTITUT
        ROLE_DEMANDEUR: ROLE_DEMANDEUR

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
