controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    methods: ['POST']

api_doc:
    path: /
    controller: api_platform.swagger_ui.action

# config/routes.yaml
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

# app.swagger:
#     path: /api/doc.json
#     methods: GET
#     defaults: { _controller: nelmio_api_doc.controller.swagger }